seed: 42
train:
  test_size: 0.2

  # Random Forest
  n_estimators: 100
  max_depth: 3

  # Logistic Regression
  logreg_max_iter: 1000
  logreg_C: 1.0
  logreg_penalty: "l2"
  logreg_solver: "lbfgs"

  # SVM
  svm_C: 1.0
  svm_kernel: "rbf"
  svm_gamma: "scale"
  svm_probability: false

  # KNN
  knn_n_neighbors: 5
  knn_weights: "uniform"
  knn_metric: "minkowski"
  knn_leaf_size: 30
  knn_p: 2

  # Naive Bayes
  nb_var_smoothing: 1e-9
